from dotenv import load_dotenv
from pydantic import BaseModel

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from langchain_classic.agents import create_tool_calling_agent, AgentExecutor #Langchain 1.x
#Old --> from langchain.agents import create_tool_calling_agent, AgentExecutor

from nutrition_tools import scrape_tool, search_tool, save_tool  

load_dotenv()

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")


class leadResponse(BaseModel):
    name: str
    calories: int
    protein: int
    fat: int
    carbohydrates: int
    tools_used: list[str]

class leadResponseList(BaseModel):
    leads: list[leadResponse]

parser = PydanticOutputParser(pydantic_object=leadResponseList)

prompt = ChatPromptTemplate.from_messages([
    ("system", 
     """
     You are a health assistant.
            1. Use the 'scrape' tool to find exactly 5 ...
            2. For each ... identified by the 'scrape' tool, use the 'search' tool to gather detailed information from DuckDuckGo.
            3. Analyze the searched website content to provide:
                - name: food name
                - calories: Any available calorie details
                - protein: Any available protein details
                - fat: Any available fat details
                - carbohydrates: Any available carbohydrates details
                - tools_used: List tools used        

            Do not include extra text beyond the formatted output and the save confirmation message.
            4. Return the output as a list of 5 entries in this format: {format_instructions}
            5. After formatting the list of 5 entries, use the 'save_to_text' tool to send the json format to the text file. 
            6. If the 'save' tool runs, say that you ran it. If you did not run the 'save' tool, say that you could not run it.

     """),
     ("human","{query}"),
     ("placeholder","{agent_scratchpad}"),
    ]
).partial(format_instructions=parser.get_format_instructions())

tools=[scrape_tool, search_tool, save_tool]

agent=create_tool_calling_agent(llm=llm, tools=tools, prompt=prompt)

agent_executor=AgentExecutor(agent=agent, tools=tools, verbose=True)

#gets user input
def get_user_query():
    return input("Ask a question about food nutrition: ")

query = get_user_query()




#The .invoke method is used to execute the agent with the given input. It takes a dictionary as an argument, where the keys correspond to the variables defined in the prompt (in this case, "query"). When you call .invoke, it processes the input through the agent's logic, which may involve calling tools, generating responses, and ultimately producing an output based on the defined prompt and the tools available. The result of .invoke is typically a structured response that can be further parsed or used as needed.
#so in this case, when you call agent_executor.invoke({"query": query}), it will execute the agent with the user's query and return the raw response generated by the agent, which may include the results from the tools used and the final output based on the prompt instructions.
#how does the query become a dictionary and what value does it hold? 
# The query is passed as a dictionary to the .invoke method because the prompt is designed to accept variables in a structured format. In this case, the prompt expects a variable named "query" which will hold the user's input. When you call get_user_query(), it prompts the user to enter their query and returns it as a string. This string is then wrapped in a dictionary with the key "query" before being passed to the .invoke method. So, if the user enters "What are some healthy foods?", the dictionary would look like {"query": "What are some healthy foods?"}. This allows the agent to access the user's input through the variable "query" defined in the prompt and use it in its processing logic.
#so hypothetically the variable "query" can be named anything as long as query matches the variable defined in the prompt. blue with blue, "" can be anything
raw_response = agent_executor.invoke({"query": query}) 

raw_output = raw_response.get('output')

if isinstance(raw_output, list):
    raw_output = ''.join(
        item['text'] if isinstance(item, dict) and item.get('type') == 'text' 
        else str(item)
        for item in raw_output
    )
#parsing output using pydantic parser. If the output is not in the expected format, it will raise an error which we catch and print the raw response for debugging.
#prints agent's response in structured format if parsing is successful, otherwise prints an error message along with the raw response for debugging purposes.
try:
    structured_response = parser.parse(raw_output)
    data = structured_response.model_dump() #pydantic v2 uses model_dump() instead of dict() to convert the model to a dictionary
    for lead in data.get('leads', []):
        print(f"""
        {lead['name']}
        Calories:      {lead['calories']} kcal
        Protein:       {lead['protein']}g
        Fat:           {lead['fat']}g
        Carbohydrates: {lead['carbohydrates']}g
        Tools used:    {', '.join(lead['tools_used'])}
""")
except Exception as e:
    print("Error parsing response", e, "Raw Response - ", raw_response)



